name: 'Telegram'
description: 'Sends a message to Telegram.'
inputs:
  bot_token:
    description: 'Bot token'
    required: true
  chat_id:
    description: 'Chat ID.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: |
        PACKAGE_NAME=$(jq -r .name package.json)
        PACKAGE_VERSION=$(jq -r .version package.json)
        TEXT=$(cat << EOF
        📦 Updated package <b><a href="https://www.npmjs.com/package/$PACKAGE_NAME">$PACKAGE_NAME</a></b>
        New version: <code>${PACKAGE_VERSION}</code>

        https://www.npmjs.com/package/$PACKAGE_NAME/v/$PACKAGE_VERSION
        EOF)
        BODY=$(jq \
          --null-input \
          --arg chat_id "$TELEGRAM_CHAT_ID" \
          --arg text "$TEXT" \
          '{"chat_id":$chat_id,"text":$text,"parse_mode":"html","link_preview_options":{"is_disabled":true}}')
        echo "$BODY"
        curl -X POST \
          -H 'Content-Type: application/json' \
          -d "$BODY" \
          https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage
      shell: bash
      env:
        TELEGRAM_BOT_TOKEN: ${{ inputs.bot_token }}
        TELEGRAM_CHAT_ID: ${{ inputs.chat_id }}
